### ISSUE TITLE
Bildüberlappungen im Slider nach wie vor vorhanden

### ISSUE THREAD

**Issue by ettka** [OKTOTV/FLUX2#29]
Bei unserem letzten Treffen hat es funktioniert - jetzt treten wieder Überlappungen beim Bildwechsel auf.
@kasabina

**Comment by kasabina** [comment]
Habe es mittlerweile gestestet mit dem Originalslider bei einer Demo von Bootstrap. Dort ist das auch vor gekommen. Es kommt nicht jedes Mal vor, bei unserem Slider auch nicht, aber immer wieder. Ist auch abhängig vom Browser usw. Das kann ich nicht beheben.
