### ISSUE TITLE
Newsumfang

### ISSUE THREAD

**Issue by SrgSteak** [OKTOTV/FLUX2#3]
Liste aller News nach Datum.

Einzuholen von Valerie Gabl: Umfang

Wie lang sind News Beiträge? 
Multimedial? Bild, Bildergalerie, Videos oder nicht? Kombinationen?

**Comment by ettka** [comment]
- Länge: das kommt ganz auf das Design und die Weiterleitungen drauf an...Orientierung s. unseren Newsletter! 
- Kombination aus Bild und Video: ja
- Bildergalerien: ja
- Möglichkeit, Posts im Voraus planen zu können

**Comment by SrgSteak** [comment]
posts im voraus planbar
Bilder und video als embed postbar
Galerien für Seiten derzeit als code umsetzbar (es kommt noch ein kopierbares snippet für seiten)
Posts bereits automatisch als Gallerie solange nur Bilder gepostet werden.
