### ISSUE TITLE
Wir brauchen noch irgendeine Reaktion wenn man eine Playlist erstellt hat mit hinzufügen in der Episode. 

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#379]
Sonst drückt man und drückt man, und dann gibt es 10 Playlisten. Ich möchte nicht einfach in deinem Script herum pfuschen. Kannst Du mir eine Funktion einrichten, in der ich so eine "Reaktion" reinschreiben kann? Z.b. einen Text oder einfärben von einem Element,... und mir dann natürlich sagen, wie die Funktion heißt :-)

**Comment by SrgSteak** [comment]
findest du genau hier: https://github.com/OKTOTV/FLUX2/blob/master/src/AppBundle/Resources/views/Episode/show.html.twig#L218
