### ISSUE TITLE
Sämtliche Posterframes werden zuerst mit .png versehen und dann dahinter noch ein .jpg

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#382]
Das heißt so ein Bildername heißt z.B. 593fda5f31d82.png_thumbnail_720x1280.jpg  Bilder dürfen aber keinen Punkt im Namen haben im Web. Das kann zu Problemen führen. Z.B. Google schreibt hin, dass das kein gültiger Bildernamen ist. Lustigerweise sind es aber nur ein paar. Vielleicht die manuell hochgeladenen? Kannst du das ändern?

**Comment by SrgSteak** [comment]
Ist mit der neuen Version des BprsAssteBundles behoben (v.2.0.37)
