### ISSUE TITLE
Übersetzungen Hilfeseite einbauen

### ISSUE THREAD

**Issue by SrgSteak** [OKTOTV/FLUX2#538]

**Comment by SrgSteak** [comment]
Kein gutes Ticket. Weder die referenzierte Seite noch die fehlenden Übersetzungen sind aus dem Ticket ersichtlich.

**Comment by kasabina** [comment]
??? Im Menü gibt es genau eine Seite die Hilfe heißt und wir haben wochenlang an genau dieser einen Seite herum gebastelt. Diese Seite muss man öffnen und die fixen Texte gegen Übersetzungsstring austauschen. Wie genau brauchst du die Beschreibung?
