### ISSUE TITLE
Suche: ich bekomme jetzt immer nur 4 Suchergebnisse bei Episoden und Serien. Hier gab es ja sogar schon eine Detailseite für mehr Suchergebnisse.

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#544]

**Comment by SrgSteak** [comment]
Grüße Sabina, bitte die Form des Tickets überarbeiten.

Beispiel:
Titel: Suchergebnisse zeigen zu wenig Resultate
Beschreibung: Es werden immer nur maximal 4 Ergebnisse angezeigt.
