### ISSUE TITLE
Eigene Newsletterseite

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#546]
... muss wie besprochen angelegt werden. Unter: http://kunden.sabinakargl.at/okto/ux/#g=1&p=newsletter findest du wie sie aussehen soll. Die Formulierung muss noch abgesegnet werden von der Rechtsanwältin.

**Comment by SrgSteak** [comment]
bereits im master a1de21b957cb453d7f028bdfddedbcf1b37ba056
