### ISSUE TITLE
TV Seite für Suchmaschine: rel Tag in Header: <link rel=\"next\" href=\"http://www.okto.tv/de/tv/.....\"> und <link rel=\"prev\" href=\"http://www.okto.tv/de/tv/.....\"> einfügen. "next" zeigt auf die komplette TV Seite mit voreingestelltem Datum der nächsten Seite und "prev" zeigt auf die komplette TV Seite mit voreingestelltem Datum der letzten Seite.

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#551]

**Comment by SrgSteak** [comment]
Grüße Sabina,

bitte die Form des Tickets überarbeiten.
Beispiel:
Titel: Crawler Meta Tags in TV Seite
Beschreibung: die Meta Tags rel="next und rel="prev" werden in der TV Seite benötigt.
Dazu muss eine komplette TV Seite mit angegebenen Tag verfügbar sein.
