### ISSUE TITLE
Die Impressumslinks in den Emails (Ordner: mail) mit der richtigen Impressumsurl versehen und dem richtigen Translationsstring.

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#565]

**Comment by SrgSteak** [comment]
Prinzipiell kein gutes Ticket. Es ist nicht genau spezifiziert welche Templates an welchen Stellen übersetzt werden sollen und mit welchem Text genau. Ich weiß es weil wir gerade eben telefoniert haben, ein dritter könnte das nicht.
