### ISSUE TITLE
Auf der Tagseite werden bei den Sendereihen 6 Ergebnisse ausgelesen statt 5 (z.B. www.okto.tv/de/tag/talk_diskurs

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#583]

**Comment by kasabina** [comment]
Vorher wurden 6 Ergebnisse angezeigt, jetzt werden dafür 4 Ergebnisse angezeigt. Bitte auf 5 korrigieren.

**Comment by SrgSteak** [comment]
hab aktuell bei dem Link 2 Sendereihen. Habe aber den Fehler gefunden.

**Comment by kasabina** [comment]
Super! Ja, da scheint was bei der Suche auch nicht zu klappen, wenn du jedesmal eine andere Ergebnisanzahl bekommst wie ich.

**Comment by SrgSteak** [comment]
Direkt bei einer Tag Seite ist keine Suche Involviert.
