### ISSUE TITLE
Passwort vergessen:

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#589]
Gibt man auf der Seite "Passwort vergessen" den falschen Usernamen an, bekommt man trotzdem die Meldung "E-Mail zum zurücksetzen des Passworts wird gesendet". Man sollte darauf hingewiesen werden, dass der Username falsch ist.

**Comment by SrgSteak** [comment]
Nein sollte man nicht, das ist eine Schutzmaßnahme da dadurch nicht bekannt wird ob tatsächlich ein User existiert
