### ISSUE TITLE
Passwort vergessen Teil 2:

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#590]
Ich habe, nach dem ich mein Passwort zurück gesetzt habe, das "Willkommensemail" noch mal bekommen. Das mit den Erklärungen, welche Möglichkeiten man hat. (welcome.html.twig). Das sollte eigentlich nur nach der Neuanmeldung geschickt werden. Beim Erneuern des Passwortes sollte kein Email kommen.

**Comment by SrgSteak** [comment]
Kann es sein dass du dein Passwort noch nicht seit der Einführung der Willkommensemail zurückgesetzt hast? Ich vermute dein "greeted" flag war noch default auf false, daher hast du nun einmalig diese E-Mail erhalten.
