### ISSUE TITLE
Producerseite Kommentare:

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#608]
Auf der Producerseite sind zwar alle Kommentare aufgelistet, diese sind aber relativ sinnlos, wenn der Producer nicht weiß, von welcher Episode diese Kommentare stammen. Eigentlich sollte er sie ja gegebenenfalls antworten können. Kann man zumindest einen Link auf die Episode legen?

**Comment by SrgSteak** [comment]
wo?

**Comment by kasabina** [comment]
Producerseite -> Aktuelle Blog- und Episodenkommentare. Leg dir eine Sendereihe an, mach Kommentare, dann siehst du es gleich auf der ersten Seite.
