### ISSUE TITLE
Passwort vergessen Teil 3:

### ISSUE THREAD

**Issue by kasabina** [OKTOTV/FLUX2#611]
Logged man sich ein, nachdem man ein neues Passwort generiert hat, kommt man auf die Seite "Seite nicht gefunden". Man sollte aber auf die Startseite kommen.

**Comment by SrgSteak** [comment]
gerade gemacht, bin auf der Startseite gelandet. Kannst du es reproduzieren?

**Comment by kasabina** [comment]
Würde ich gerne, aber ich kann mich nicht abmelden. Ich bin jetzt dreimal auf Abmelden gegangen. Wurde da was geändert?

**Comment by kasabina** [comment]
ja, hab ich dann gemacht und ist gegangen. Also: bei neuerlichem Zusenden hat es jetzt auch geklappt, ich bin auch auf die Startseite gekommen. Ich habe jetzt aber gleich darauf wieder probiert mich auszuloggen und bin auf: https://www.okto.tv/backend/logout mit "Seite nicht gefunden" Ansicht gekommen. Ausgelogged bin ich aber wieder nicht. Ich probiere es noch in einem anderen Browser.
