### ISSUE TITLE
Zugeschnittenes Bildmaterial wird nach Zuschneiden nicht korrekt dargestellt

### ISSUE THREAD

**Issue by ettka** [OKTOTV/FLUX2#66]
![vorher](https://cloud.githubusercontent.com/assets/11075648/16227290/1515ac9a-37b0-11e6-8281-a0b02f534f17.png)
![nachher](https://cloud.githubusercontent.com/assets/11075648/16227307/2d5e9334-37b0-11e6-9e29-68c2cb3650be.png)

**Comment by SrgSteak** [comment]
fixed in BPRSAssetBundle. Rollout pending.
